name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd src
        cd MyProgrammerAll
        dotnet restore        
    - name: Build
      run: |
        cd src
        cd MyProgrammerAll
        cd MyProgrammerAllConsole
        dotnet build --no-restore
        dotnet pack --no-build --include-source -o PACK
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: PackTool
        path: 'src/MyProgrammerAll/MyProgrammerAllConsole/pack/'
        retention-days: 1        